hh

diff --git a/.github/workflows/test-suite.yaml b/.github/workflows/test-suite.yaml
--- a/.github/workflows/test-suite.yaml
+++ b/.github/workflows/test-suite.yaml
@@ -103,56 +103,71 @@ jobs:
           docker exec cms-db mysql -ucms -pjenkins cms -e "INSERT INTO task (name, class, status, isActive, configFile, options, schedule) VALUES ('Seed Database', '\\\\Xibo\\\\XTR\\\\SeedDatabaseTask', 2, 1, '/tasks/seed-database.task', '{}', '* * * * * *')"
           docker exec --user www-data -t cms-web /bin/bash -c "cd /var/www/cms; /usr/bin/php bin/run.php \"Seed Database\""
           sleep 5
+
+
       - name: Run Cypress
         id: cypress
         run: |
-          docker exec cms-db mysql -ucms -pjenkins cms -e "INSERT INTO oauth_clients (id, secret, name, userId, authCode, clientCredentials) VALUES ('MrGPc7e3IL1hA6w13l7Ru5giygxmNiafGNhFv89d', 'Pk6DdDgu2HzSoepcMHRabY60lDEvQ9ucTejYvc5dOgNVSNaOJirCUM83oAzlwe0KBiGR2Nhi6ltclyNC1rmcq0CiJZXzE42KfeatQ4j9npr6nMIQAzMal8O8RiYrIoono306CfyvSSJRfVfKExIjj0ZyE4TUrtPezJbKmvkVDzh8aj3kbanDKatirhwpfqfVdfgsqVNjzIM9ZgKHnbrTX7nNULL3BtxxNGgDMuCuvKiJFrLSyIIz1F4SNrHwHz', 'cypress', 1, 0, 1)"
-          docker exec cms-db mysql -ucms -pjenkins cms -e "INSERT INTO oauth_client_scopes (clientId, scopeId) VALUES ('MrGPc7e3IL1hA6w13l7Ru5giygxmNiafGNhFv89d', 'all') ON DUPLICATE KEY UPDATE scopeId = scopeId"
-          if [[ "$test_all" == true ]]; then
-            docker run --ipc=host --name cms-cypress --link=cms-web:web -v $(pwd)/cypress.config.js:/app/cypress.config.js -v $(pwd)/cypress:/app/cypress ghcr.io/xibosignage/xibo-cms:cypress npx testmo automation:resources:add-field --name git --type string --value ${GITHUB_SHA:0:7} --resources resources.json
-          else
-            docker run --ipc=host --name cms-cypress --link=cms-web:web -v $(pwd)/cypress.config.js:/app/cypress.config.js -v $(pwd)/cypress:/app/cypress ghcr.io/xibosignage/xibo-cms:cypress bash -c "CYPRESS_baseUrl=http://web /app/node_modules/.bin/cypress run --config screenshotsFolder=/app/cypress/results,video=false --spec \"$spec_content\" --reporter junit --reporter-options 'mochaFile=/app/cypress/results/results_cypress_[hash].xml,toConsole=true' && chown -R 1001:1001 /app/cypress/results && exit \${PIPESTATUS[0]};"
-          fi
-        continue-on-error: true
+          docker run \
+            --ipc=host \
+            --name cms-cypress \
+            --link=cms-web:web \
+            -v $(pwd)/cypress.config.js:/app/cypress.config.js \
+            -v $(pwd)/cypress:/app/cypress \
+            ghcr.io/xibosignage/xibo-cms:cypress \
+            bash -c "echo 'NPM Version:' && npm --version
 
-      - name: Save Cypress test results as an artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: cypress-test-results
-          path: cypress/results
 
-      - name: Check Cypress exit code
-        run: |
-          if [[ ${{ steps.cypress.outcome }} == 'success' ]]; then
-            echo "Cypress tests succeeded"
-          else
-            echo "Cypress tests failed with exit code ${{ steps.cypress.exitCode }}"
-            exit 1
-          fi
-
-      # Step 5: Add a comment to the PR with the workflow result
-      - name: Add workflow result as comment on PR
-        uses: actions/github-script@v6
-        if: always()
-        with:
-          script: |
-            const name = '${{ github.workflow }}';
-            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
-            const success = '${{ job.status }}' === 'success';
-            const body = `${name}: ${success ? 'succeeded ✅' : 'failed ❌'}\n${url}`;
-
-            await github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: body
-            })
-
-      # Step 6: Set the status of the latest commit to the final job status
-      - name: Set latest commit status as ${{ job.status }}
-        uses: myrotvorets/set-commit-status-action@master
-        if: always()
-        with:
-          sha: ${{ steps.comment-branch.outputs.head_sha }}
-          token: ${{ secrets.GITHUB_TOKEN }}
-          status: ${{ job.status }}
+#      - name: Run Cypress2
+#        id: cypress
+#        run: |
+#          docker exec cms-db mysql -ucms -pjenkins cms -e "INSERT INTO oauth_clients (id, secret, name, userId, authCode, clientCredentials) VALUES ('MrGPc7e3IL1hA6w13l7Ru5giygxmNiafGNhFv89d', 'Pk6DdDgu2HzSoepcMHRabY60lDEvQ9ucTejYvc5dOgNVSNaOJirCUM83oAzlwe0KBiGR2Nhi6ltclyNC1rmcq0CiJZXzE42KfeatQ4j9npr6nMIQAzMal8O8RiYrIoono306CfyvSSJRfVfKExIjj0ZyE4TUrtPezJbKmvkVDzh8aj3kbanDKatirhwpfqfVdfgsqVNjzIM9ZgKHnbrTX7nNULL3BtxxNGgDMuCuvKiJFrLSyIIz1F4SNrHwHz', 'cypress', 1, 0, 1)"
+#          docker exec cms-db mysql -ucms -pjenkins cms -e "INSERT INTO oauth_client_scopes (clientId, scopeId) VALUES ('MrGPc7e3IL1hA6w13l7Ru5giygxmNiafGNhFv89d', 'all') ON DUPLICATE KEY UPDATE scopeId = scopeId"
+#          if [[ "$test_all" == true ]]; then
+#            docker run --ipc=host --name cms-cypress --link=cms-web:web -v $(pwd)/cypress.config.js:/app/cypress.config.js -v $(pwd)/cypress:/app/cypress ghcr.io/xibosignage/xibo-cms:cypress npx testmo automation:resources:add-field --name git --type string --value ${GITHUB_SHA:0:7} --resources resources.json
+#          else
+#            docker run --ipc=host --name cms-cypress --link=cms-web:web -v $(pwd)/cypress.config.js:/app/cypress.config.js -v $(pwd)/cypress:/app/cypress ghcr.io/xibosignage/xibo-cms:cypress bash -c "CYPRESS_baseUrl=http://web /app/node_modules/.bin/cypress run --config screenshotsFolder=/app/cypress/results,video=false --spec \"$spec_content\" --reporter junit --reporter-options 'mochaFile=/app/cypress/results/results_cypress_[hash].xml,toConsole=true' && chown -R 1001:1001 /app/cypress/results && exit \${PIPESTATUS[0]};"
+#          fi
+#        continue-on-error: true
+#
+#      - name: Save Cypress test results as an artifact
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: cypress-test-results
+#          path: cypress/results
+#
+#      - name: Check Cypress exit code
+#        run: |
+#          if [[ ${{ steps.cypress.outcome }} == 'success' ]]; then
+#            echo "Cypress tests succeeded"
+#          else
+#            echo "Cypress tests failed with exit code ${{ steps.cypress.exitCode }}"
+#            exit 1
+#          fi
+#
+#      # Step 5: Add a comment to the PR with the workflow result
+#      - name: Add workflow result as comment on PR
+#        uses: actions/github-script@v6
+#        if: always()
+#        with:
+#          script: |
+#            const name = '${{ github.workflow }}';
+#            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
+#            const success = '${{ job.status }}' === 'success';
+#            const body = `${name}: ${success ? 'succeeded ✅' : 'failed ❌'}\n${url}`;
+#
+#            await github.rest.issues.createComment({
+#              issue_number: context.issue.number,
+#              owner: context.repo.owner,
+#              repo: context.repo.repo,
+#              body: body
+#            })
+#
+#      # Step 6: Set the status of the latest commit to the final job status
+#      - name: Set latest commit status as ${{ job.status }}
+#        uses: myrotvorets/set-commit-status-action@master
+#        if: always()
+#        with:
+#          sha: ${{ steps.comment-branch.outputs.head_sha }}
+#          token: ${{ secrets.GITHUB_TOKEN }}
+#          status: ${{ job.status }}
